@startuml

title Calculate() operation - Calculator Class 


start

:get Input; 
note right: calculate(input)//parameter

:object data members: val:String,reg:String,tmpReg:boolean, reg:String; 
note left: declared at class level
:val= " ", reg= " ", op="", tmpReg=false;
note right: initialised at class level

if (input is 0 to 9 && !tmpReg ) then (yes)
  :val+=input;
  note right: concatenate value
else if(input is 0 to 9 && tmpReg) then (yes)
  :reg+=input;
  note right: concatenate tmpReg
else if(input is "." && !tmpReg ) then (yes)
  :val+=input;
else if(input is 0 to 9 && tmpReg) then (yes)
  :reg+=input;
else if(input is op && !tmpReg ) then (yes)
  :op=input;
  :tmpReg=true;
  :reg="";
else if(input is op && tmpReg) then (yes)
  :perform operation;
  :op=input;
  :reg="";
else if(input is "=" && !tmpReg ) then (yes)
  ://do nothing;
else if(input is "=" && tmpReg) then (yes)
  :perform operation;
  :reg="";
else if(input is "C" && !tmpReg ) then (yes)
  :val="";
else if(input is "C" && tmpReg) then (yes)
  :reg="";
else if(input is "AC") then (yes)
  :val="";
  :reg="";
  :tmpReg=false;
else (no)
  ://do nothing;
endif

stop

@enduml